### ISSUE TITLE
关于forward trace的问题

### ISSUE THREAD

**Issue by zhanjw** [threeYANG/mmdetection_libtorch#5]
请问为何forward trace中将rpn和extracted feature concat之后平铺成n*1输出？
是因为将模型输出后处理放在c++中，只在部署时才还原对应的shape吗？可否直接对应输出，将整个模型trace成一个完整的pt model，以减少对齐成本？
另外，bone的pt model中包含有roi_head和bbox_head等模型信息，只是没有使用而已？
也就是说如果要将mmdetection部署到c++上，需要自己实现c++的mmdet吗？感觉这样就失去了torchscript的优势
另外，shared_head在faster rcnn中好像没有用到，如果只部署faster rcnn，是冗余的吗？非常感谢回复。

**Comment by threeYANG** [comment]
时间久了，有些不记得了，只能按照印象回答。1、rpn数据流tensor和feature的数据流tensor都需要输出出去，但是trace只接受tensor，所以把两个拼接成一个tensor。2、roi_head和bbox_head的参数不能直接从pt  model过去，需要另外保存和存存取，rpn后面的代码也需要在libtorch中重现，是因为mmdetection  中的faster rcnn 的整个网络不能被trace，trace只能跟踪tensor流，faster  rcnn 
 在roi的入口有非tensor数据。这就是为什么trace  的时候，要写forward_trace函数了。3、shared_head是mask rcnn用到的，我写这个主要是熟悉lib torch的部署方式，真的部署的时候，很多东西需要优化，另外，我觉得tensort更适合部署，比lib torch更快。       说的不详细，大方向是这样的

**Comment by zhanjw** [comment]
非常感谢！受益匪浅
